### PR TITLE
Update zip.py

### PR DESCRIPTION
**Pull request by KUndn**
imported valid_ip.py as a module and implemented is_valid() function from the module.

### CODE REVIEW

**Comment by achoudh5** [comment]
Thank you @KUndn for your contribution!

**Comment by KUndn** [comment]
Thanks

**Comment by achoudh5** [comment]
Hi @KUndn 

Upon running, it gave me error:-

`    wb = openpyxl.load_workbook(i)
NameError: name 'i' is not defined
`

Seems like `valid_ip.py` doesn't know about the variable `i` you transferred from `zip.py`

Can you fix it?

**Comment by KUndn** [comment]
Hi @achoudh5 
`wb = openpyxl.load_workbook(i)`
in above statement `i` is input variable and `valid.py` doesnot take any input
`i` is not passed from `zip.py ` folder.

that's all i can deduce from what i know, 
if that's correct i can just uncomment the input statement .
Correct me if  i am wrong.

**Comment by achoudh5** [comment]
Yea, that's correct understanding! Make sure that is_valid function is working maybe use a print statement. 
If you can paste some output as well that'll simply things for me 😃

**Pull request merged**
