### PR TITLE
Updating readme

### PR DESCRIPTION
**Pull request by KUndn**
modified readme and added git and github tutorial for making pull request

### CODE REVIEW

**Review by achoudh5 — COMMENTED** [review]
this looks great @KUndn !

**Comment by achoudh5** [comment]
Thank you @KUndn for this contribution :)

**Comment by KUndn** [comment]
> Thank you @KUndn for this contribution :)

thanks

**Comment by achoudh5** [comment]
> > Thank you @KUndn for this contribution :)
> 
> thanks

@KUndn check in this PR, the label is added. We don't need it but still I have it on all PR's approved :)

**Comment by KUndn** [comment]
> > > Thank you @KUndn for this contribution :)
> > 
> > 
> > thanks
> 
> @KUndn check in this PR, the label is added. We don't need it but still I have it on all PR's approved :)

thanks for the label . you the best 💯

**Pull request merged**
